### PR TITLE
Added support for tezos.

### PR DESCRIPTION
**Pull request by vivekascoder**
This PR includes the code to support the tezos specific metadata for NFTs. Tezos follows [TZIP-12 Standard](https://gitlab.com/tezos/tzip/-/blob/master/proposals/tzip-21/tzip-21.md#fungible-token-recommendations). Also tezos NFT metadata needs the different sizes of artwork to use as a thumbnail and display that's why we need to resize the existing images generated from yarn build.

I've added resize.js which uses the sharp module to resize the images generated in the utils/ directory.

Please let me know any changes from your side.

Since it has different properties in metadata, to update the metadata I've created a separate file in the Tezos/ directory that updates certain properties of the metadata.

Example of tezos NFT metadata: https://ipfs.infura.io:5001/api/v0/cat?arg=QmNQ6ARwXfEFQSNCC3BiK1giv5njF6mx8nGBJckLYyzy9T

### CODE REVIEW

**Comment by vivekascoder** [comment]
@nftchef  Let me know if you want me to change something or follow a certain way to organize code, thanks.

**Review by nftchef — COMMENTED** [review]
Thank you for this! only one small comment in package.json. 

It would be great if you could start a basic readme in /other-blockchains 
and one for the resize script in /documentation/utils, either as part of this PR if you have time or as a separate one later.

**Comment by vivekascoder** [comment]
Hey, I did the required changes, have a look and let me know.

**Comment by nftchef** [comment]
@vivekascoder FANTASTIC! Thank you so much!

**Pull request merged**
